#34 add equation
ani119/ProjektGrupowy pull request #40
Opened 2020-04-23 09:19 UTC by Wiki13002

-equation display
-enter the result of the equation

2020-04-23 09:24 UTC, ani119 commented
@Wiki13002 please reslove conflicts

2020-04-23 09:25 UTC, ani119 commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Equation.cs
> +    int x;
We use English name of variables and functions, please look to ours code and stay in the same pattern.

2020-04-23 09:26 UTC, ani119 commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Equation.cs
> +    public InputField odpowiedz;
public variables should be upper than private ones

2020-04-23 09:27 UTC, ani119 commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Equation.cs
> +        x = Random.Range(2, 11);
We exclude 1*2 ? And why there is (2,11)?

2020-04-23 09:28 UTC, ani119 commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Equation.cs
> +            blad.text = "spróbuj jeszcze raz";
Let's start it with big letter

2020-04-23 09:29 UTC, ani119 commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Equation.cs
> +    public Text napisRownanie;
We use English name of variables and functions, please look to ours code and stay in the same pattern.

2020-04-23 09:31 UTC, ani119 commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Equation.cs
> +public class Script : MonoBehaviour
Please name this script with count what it do (ofc in English)

2020-04-23 09:34 UTC, ani119 requested changes
As I wrote in single comments this code needs some work, pleace use pattern which all team use - english names of variables and functions (remember about names gameobjects in scene hierarchy too). Your script should have name which suggest what the script do. Some refactoring about the variable order, as I wrote a few times the public ones should be higher. More comments are written at specific lines. Please remeber to be up to date with your branch and don't have conflicts.

2020-04-23 15:51 UTC, przemytka commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Equation.cs
> +            blad.text = "spróbuj jeszcze raz";
Capital letter* :P

2020-04-25 13:25 UTC, ani119 submitted a review, later dismissed
Good job!

2020-04-25 18:16 UTC, przemytka submitted a review, later dismissed

2020-04-26 09:56 UTC, AgaMazur requested changes
Delete unnecessary empty lines in 'multiplication' code

2020-04-27 22:07 UTC, ani119 approved these changes

2020-04-28 07:56 UTC, przemytka approved these changes

2020-04-28 08:17 UTC, juliakobusinska98 approved these changes

2020-04-28 09:33 UTC, merged