#44 modal every 10
ani119/ProjektGrupowy pull request #53
Opened 2020-05-05 09:22 UTC by AgaMazur

- modal every 10 equations
- count % of correct answears 
- show stars for under 50%, above 50% and 70%

2020-05-05 09:25 UTC, juliakobusinska98 submitted a review, later dismissed

2020-05-05 17:52 UTC, ani119 requested changes
It almost good, only some suggestions:
- firstly we shouldn't have many types of modals in canvas
- every modal should base on one 'base modal'
- your class RatingModal should inherit of Modal
- RatingModal should not count total and tries it is a GameController role
RatingModal should include:
- display text
- display starts
- not count anything ( the total and tries values should be taken from game controller, where you will display it)

I propose to use names firstStar, secondStar, thirdStar or better starFirst,....
Usualy we are trying not to use numbers at variable names 

You don't have last commits from add base scenes from my last 2 pull requests

2020-05-07 18:55 UTC, AgaMazur commented
Rebased and force pushed.

2020-05-08 12:54 UTC, ani119 approved these changes

2020-05-08 13:05 UTC, juliakobusinska98 approved these changes

2020-05-08 21:44 UTC, przemytka approved these changes

2020-05-08 21:44 UTC, merged