#58 add delete shoal
ani119/ProjektGrupowy pull request #59
Opened 2020-05-11 20:53 UTC by ani119

- add chest with collider
- add to all shoal prefabs colliders and rigitbody
- add OnTriggerEnter2D function

![image](https://user-images.githubusercontent.com/28688967/81610571-0ab4dc00-93da-11ea-8110-0cd38943fceb.png)

![image](https://user-images.githubusercontent.com/28688967/81610605-156f7100-93da-11ea-99ab-72bc50cfa39a.png)

2020-05-12 10:16 UTC, przemytka requested changes
Da chest ain't gonna eat da fish :(

2020-05-12 10:45 UTC, ani119 commented
> Da chest ain't gonna eat da fish :(

I will check it after work, locally it worked fine...

2020-05-12 17:55 UTC, przemytka submitted a review, later dismissed

2020-05-12 18:03 UTC, przemytka approved these changes

2020-05-13 18:09 UTC, AgaMazur approved these changes

2020-05-13 18:49 UTC, juliakobusinska98 approved these changes

2020-05-13 18:49 UTC, merged