#49 Connect modal with equitation
ani119/ProjektGrupowy pull request #60
Opened 2020-05-12 16:39 UTC by Wiki13002

-after click enter appear modal with right conent
-the text which is displayed under input is deleted

2020-05-12 17:29 UTC, ani119 requested changes
It isn't work. I had the error: 
NullReferenceException: Object reference not set to an instance of an object
Modal.setModalTextContent (System.String userName, System.Boolean isPositive) (at Assets/Scritps/Components/Modal.cs:31)
Modal.setMessage (System.String playerName, System.Boolean isPositive) (at Assets/Scritps/Components/Modal.cs:16)
GameController.modalControl () (at Assets/Scritps/Controllers/GameController.cs:27)
GameController.Update () (at Assets/Scritps/Controllers/GameController.cs:17)

2020-05-12 17:29 UTC, ani119 commented on podwodny_swiat_tabliczki_mnozenia/Assets/Scritps/Controllers/GameController.cs
> +    bool IsWaitingForAnswert = true;
Let's move this variable before all methods. I propose to change name to isWaitingForAnswer

2020-05-13 18:24 UTC, ani119 approved these changes

2020-05-13 18:34 UTC, juliakobusinska98 approved these changes

2020-05-13 20:24 UTC, AgaMazur approved these changes

2020-05-13 20:24 UTC, merged