#77 Add scene with blanks
ani119/ProjektGrupowy pull request #78
Opened 2020-11-07 19:10 UTC by ani119

![image](https://user-images.githubusercontent.com/28688967/98449608-26a0fc80-2135-11eb-8760-1e542338c3ec.png)

2020-11-07 19:27 UTC, juliakobusinska98 approved these changes

2020-11-07 19:50 UTC, AgaMazur approved these changes

2020-11-07 23:20 UTC, juliakobusinska98 requested changes
Scene 'NumbersGame' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.

2020-11-09 11:43 UTC, juliakobusinska98 approved these changes

2020-11-09 11:43 UTC, przemytka approved these changes

2020-11-09 11:43 UTC, merged